import { BaseMakeRequestParams, MakeRequestConfig } from './make';

export interface CreateFolderParams extends BaseMakeRequestParams {
  teamId: number;
  name: string;
}

// Generated by https://quicktype.io

export interface CreateFolderOutput {
  scenarioFolder: ScenarioFolder;
}

export interface ScenarioFolder {
  id: number;
  name: string;
  scenariosTotal: number;
}

export function createFolder(params: CreateFolderParams): MakeRequestConfig {
  const requestConfig: MakeRequestConfig = {
    method: 'post',
    path: '/scenarios-folders',
    body: params,
  };
  return requestConfig;
}

export interface DeleteFolderParams {
  folderId: number;
}

export interface DeleteFolderOutput {
  scenarioFolder: number;
}

export function deleteFolder(params: DeleteFolderParams): MakeRequestConfig {
  const requestConfig: MakeRequestConfig = {
    method: 'delete',
    path: `/scenarios-folders/${params.folderId}`,
  };
  return requestConfig;
}

export interface UpdateFolderParams extends ScenarioFolder{
  scenarioFolderId: number;
}

export interface UpdateFolderOutput {
  scenarioFolder: ScenarioFolder;
}

export function updateFolder(params: UpdateFolderParams): MakeRequestConfig {
  const requestConfig: MakeRequestConfig = {
    method: 'patch',
    path: `/scenarios-folders/${params.scenarioFolderId}`,
    body: { ...params }
  };
  return requestConfig;
}

export interface ListFoldersParams {
  teamId: number;
}
export interface ListFoldersOutput {
  scenariosFolders: ScenariosFolder[];
}

export interface ScenariosFolder {
  id:             number;
  name:           string;
  scenariosTotal: number;
}

export function listFolders(params: ListFoldersParams): MakeRequestConfig {
  const requestConfig: MakeRequestConfig = {
    method: 'get',
    path: '/scenarios-folders',
    queryStringObject: { ...params }
  };
  return requestConfig;
}
